# Site settings
title: 旭旭
description: "众人皆醒而我独醉 ..."
baseurl: "/" # the subpath of your site
url: "http://xuhongxu.com"

# User settings
username: xuhongxu96
user_title: Hongxu Xu
email: xuhongxu96@gmail.com
twitter_username: Xuhongxu_it
github_username:  xuhongxu96
gplus_username:  
disqus_username: xuhongxu-it

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: BNU-Xiaoya (android)
    url: https://github.com/xuhongxu96/BNU-Xiaoya
  - name: regex2dfa (python)
    url: https://github.com/xuhongxu96/regex2dfa
  - name: Tagexing - public bike management system (php/laravel)
    url: https://github.com/xuhongxu96/tagexing2
  - name: BNU-Schoolwork-Assist (python)
    url: https://github.com/xuhongxu96/BNU-Schoolwork-Assist
  - name: Qt-BNU-Gateway (qt)
    url: https://github.com/xuhongxu96/Qt-BNU-Gateway
  - name: Web-BNU-Gateway (web)
    url: https://github.com/xuhongxu96/Web-BNU-Gateway
  - name: BNU-Media (web)
    url: https://github.com/xuhongxu96/BNU-Media
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
